### ISSUE TITLE
[URDF] KneePitch and HipPitch, mimic joints?

### ISSUE THREAD

**Issue by jokla** [ros-naoqi/pepper_robot#25]
Hi!

I have noticed that  KneePitch and HipPitch are mimic joints. If I move one, automatically the other one is moving. I guess for stability reason. I did not find information concerning this point in the documentation.

1) Shouldn't they be described as mimic joints in the URDF?
2) If I want to use a whole body control (taking care of the stability), is it possible to disable the mimic mechanism?

Thanks!

**Comment by mikaelarguedas** [comment]
Hi,

I don't have a pepper available for testing it but I think that there is no mechanical coupling between these joints. I think the mimic behaviour you are referring to is a software one provided by ALMotion (like you I'd assume it's for stability purposes).

One way to confirm it would be to bypass motion and  send a command to DCM for only one of these 2 joints and see if the other one moves.

I don't know how you can tell ALmotion not to couple them though. If you want to use your own whole body controller you may want to disable completely motion and send commands directly to individual joints.

Sorry it's not a very useful answer, hopefully someone will be able to complete it.

**Comment by jokla** [comment]
Hi Mikael,

Thank you very much for your answer. I can try with the DCM but I would be interested to know the coupling coefficient between the two joints. In this way, I can estimate the Jacobian and leave ALMotion taking care of the stability. To whom could I ask?  Maybe @nlyubova  can tell me more?

Thank you!

Giovanni

**Comment by sbarthelemy** [comment]
Hi Jokla,

As Mikael said, KneePitch and HipPitch are independent degrees of freedom. As such they must not be described as mimic joints in the URDF.

Those joints have a big oimpact on the center of mass position and are often used together to ensure the robot balance, but there is no constant coupling coefficient between them.

If you want to keep ALMotion running, you may try to send commands to both KneePitch and HipPitch in the same call and ensure the commands keep the center of mass centered, so that ALMotion's balance algorithm does not interfere too much.

Hope it helps!
-- Sébastien

**Comment by jokla** [comment]
Hi Sébastien,

Ok perfect, thanks for the explanation. 
I will try to send commands to both KneePitch and HipPitch in the same call.

Giovanni

**Comment by suryaambrose** [comment]
Hi @jokla ,

Can this issue be closed ?

**Comment by jokla** [comment]
@suryaambrose , yes! Thanks
