### ISSUE TITLE
how to publish TF for fingers

### ISSUE THREAD

**Issue by k-okada** [ros-naoqi/pepper_robot#8]
When I started from pepper_full.launch , it seems they are missing fingers. Whereas if we use pepper_full_py.launch we can see fingers. How do we fix them?

![screenshot from 2015-10-01 19 52 16](https://cloud.githubusercontent.com/assets/493276/10219174/996ef6da-6877-11e5-9c9a-22085c6ac03c.png)

**Comment by Karsten1987** [comment]
It's the way we incorporated the robot state publisher inside the C++ bridge and parse the URDF. We simply copied the robot state publisher code to have a single executable for the bridge (cross-compilation via qibuild). I however can't tell you directly why the fingers are not parsed, since we publish dynamic and fixed transformations. 
You can have a look at this: https://github.com/ros-naoqi/naoqi_driver/blob/master/src/converters/joint_state.cpp#L93

The difference to the python bridge is thus that we execute the robot state publisher locally.
